# Generated by Django 3.1.5 on 2021-04-16 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=30)),
                ('cognom', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=40)),
                ('telefon', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id_pelicula', models.AutoField(primary_key=True, serialize=False)),
                ('titol', models.CharField(max_length=30)),
                ('sinopsis', models.TextField()),
                ('generes', models.CharField(max_length=30)),
                ('duracio', models.CharField(max_length=5)),
                ('director', models.CharField(max_length=30)),
                ('actors', models.CharField(max_length=100)),
                ('puntuacio', models.CharField(max_length=5)),
                ('imatge', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producte',
            fields=[
                ('id_producte', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('preu', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id_sala', models.AutoField(primary_key=True, serialize=False)),
                ('num_sala', models.IntegerField()),
                ('detalls', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Sessio',
            fields=[
                ('id_sessio', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('id_pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestio_cine.pelicula')),
                ('id_sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestio_cine.sala')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestio_cine.client')),
                ('id_sessio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestio_cine.sessio')),
            ],
        ),
        migrations.CreateModel(
            name='Fila',
            fields=[
                ('id_fila', models.AutoField(primary_key=True, serialize=False)),
                ('num_fila', models.IntegerField()),
                ('id_sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestio_cine.sala')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='id_producte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestio_cine.producte'),
        ),
        migrations.CreateModel(
            name='Butaca',
            fields=[
                ('id_butaca', models.AutoField(primary_key=True, serialize=False)),
                ('num_butaca', models.IntegerField()),
                ('id_sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestio_cine.fila')),
            ],
        ),
    ]
