# Generated by Django 3.1.5 on 2021-04-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestio_cine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='qualificacio',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
