# Generated by Django 3.1.5 on 2021-04-21 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestio_cine', '0003_auto_20210419_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id_producte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestio_cine.producte'),
        ),
        migrations.AlterModelTable(
            name='client',
            table='gestio_cine_client',
        ),
    ]
