# Generated by Django 3.1.5 on 2021-04-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestio_cine', '0004_auto_20210421_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='imatge',
            field=models.ImageField(upload_to=''),
        ),
    ]
