# Generated by Django 3.1.5 on 2021-04-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestio_cine', '0008_auto_20210422_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='generes',
            field=models.CharField(choices=[('Acció', 'Acció'), ('Animació', 'Animació'), ('Terror', 'Terror'), ('Suspens', 'Suspens'), ('Aventura', 'Aventura'), ('Comèdia', 'Comèdia'), ('Romance', 'Romance')], max_length=30),
        ),
    ]
