# Generated by Django 3.1.5 on 2021-05-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestio_cine', '0010_producte_imatge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='detalls',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
