# Generated by Django 3.1.5 on 2021-05-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestio_cine', '0011_auto_20210503_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='titol',
            field=models.CharField(max_length=80),
        ),
    ]
