# Generated by Django 3.1.5 on 2021-05-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestio_cine', '0013_auto_20210504_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='imatge',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
