# Generated by Django 3.1.5 on 2021-05-06 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestio_cine', '0014_auto_20210504_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='data',
        ),
    ]
