# Generated by Django 3.1.5 on 2021-05-07 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestio_cine', '0015_remove_reserva_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='id_pelicula',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='gestio_cine.pelicula'),
            preserve_default=False,
        ),
    ]
