# Generated by Django 3.2.2 on 2021-05-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestio_cine', '0017_auto_20210511_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='id_genere',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='generes',
            field=models.CharField(choices=[('Acció', 'Acció'), ('Animació', 'Animació'), ('Terror', 'Terror'), ('Suspens', 'Suspens'), ('Aventura', 'Aventura'), ('Comèdia', 'Comèdia'), ('Romance', 'Romance')], default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Generes',
        ),
    ]
