# Generated by Django 3.2.2 on 2021-05-11 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestio_cine', '0021_pelicula_id_genere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='id_genere',
        ),
        migrations.DeleteModel(
            name='Generes',
        ),
    ]
