# Generated by Django 3.2.2 on 2021-05-11 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestio_cine', '0033_pelicula_id_genere'),
    ]

    operations = [
        migrations.RenameField(
            model_name='butaca',
            old_name='id_sala',
            new_name='id_fila',
        ),
    ]
