# Generated by Django 3.2.2 on 2021-05-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestio_cine', '0034_rename_id_sala_butaca_id_fila'),
    ]

    operations = [
        migrations.AddField(
            model_name='butaca',
            name='disponible',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='preu',
            field=models.FloatField(default=6),
            preserve_default=False,
        ),
    ]
