# Generated by Django 3.2.2 on 2021-05-14 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestio_cine', '0035_auto_20210513_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='butaca',
            old_name='disponible',
            new_name='ocupat',
        ),
    ]
