# Generated by Django 3.2.2 on 2021-05-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestio_cine', '0036_rename_disponible_butaca_ocupat'),
    ]

    operations = [
        migrations.AddField(
            model_name='butaca',
            name='sessio',
            field=models.ManyToManyField(to='gestio_cine.Sessio'),
        ),
    ]
