# Generated by Django 3.2.2 on 2021-05-18 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestio_cine', '0037_butaca_sessio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='butaca',
            name='sessio',
        ),
    ]
