# Generated by Django 3.2.2 on 2021-05-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestio_cine', '0039_auto_20210518_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='butaca_sessio',
            name='id',
        ),
        migrations.AddField(
            model_name='butaca_sessio',
            name='id_butaca_sessio',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
