# Generated by Django 3.2.2 on 2021-05-18 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestio_cine', '0041_auto_20210518_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='butaca',
            name='sessio',
        ),
        migrations.DeleteModel(
            name='Butaca_Sessio',
        ),
    ]
