# Generated by Django 3.2.2 on 2021-05-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestio_cine', '0044_auto_20210518_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='butaca',
            name='sessio',
        ),
        migrations.AddField(
            model_name='butaca',
            name='ocupat',
            field=models.BooleanField(null=True),
        ),
        migrations.DeleteModel(
            name='Butaca_Sessio',
        ),
    ]
