# Generated by Django 3.2.2 on 2021-05-18 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestio_cine', '0045_auto_20210518_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='butaca',
            name='ocupat',
        ),
    ]
