# Generated by Django 3.2.2 on 2021-05-18 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestio_cine', '0048_auto_20210518_1229'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Butaca_Sessio',
        ),
    ]
