# Generated by Django 3.2.2 on 2021-05-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestio_cine', '0050_butaca_id_sessio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='butaca',
            name='id_sessio',
        ),
        migrations.AddField(
            model_name='butaca',
            name='ocupat',
            field=models.BooleanField(null=True),
        ),
    ]
