# Generated by Django 3.2.2 on 2021-05-18 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestio_cine', '0051_auto_20210518_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='detalls',
        ),
    ]
