# Generated by Django 3.2.2 on 2021-05-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestio_cine', '0054_remove_butaca_ocupat'),
    ]

    operations = [
        migrations.AddField(
            model_name='butaca',
            name='reserva',
            field=models.ManyToManyField(to='gestio_cine.Reserva'),
        ),
    ]
