# Generated by Django 3.2.2 on 2021-05-20 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestio_cine', '0055_butaca_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='id_client',
        ),
    ]
