# Generated by Django 3.2.2 on 2021-05-21 06:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestio_cine', '0056_remove_reserva_id_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentari',
            fields=[
                ('id_comentari', models.AutoField(primary_key=True, serialize=False)),
                ('comentari', models.TextField()),
                ('data', models.DateField(default=datetime.date.today)),
                ('id_usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
