# Generated by Django 3.2.2 on 2021-05-21 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestio_cine', '0059_remove_comentari_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentari',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
