# Generated by Django 3.2.2 on 2021-05-21 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestio_cine', '0060_comentari_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='butaca',
            name='reserva',
        ),
    ]
