# Generated by Django 3.2.2 on 2021-05-21 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestio_cine', '0061_remove_butaca_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Butaca_Reserves',
            fields=[
                ('id_butaca_reserves', models.AutoField(primary_key=True, serialize=False)),
                ('id_butaca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestio_cine.butaca')),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestio_cine.reserva')),
            ],
        ),
        migrations.AddField(
            model_name='butaca',
            name='reserva',
            field=models.ManyToManyField(through='gestio_cine.Butaca_Reserves', to='gestio_cine.Reserva'),
        ),
    ]
