# Generated by Django 3.2.2 on 2021-06-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestio_cine', '0062_auto_20210521_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='duracio',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='qualificacio',
            field=models.IntegerField(max_length=2),
        ),
    ]
