# Generated by Django 3.2.2 on 2021-06-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestio_cine', '0064_auto_20210605_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuari',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
