# Generated by Django 3.2.2 on 2021-06-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestio_cine', '0068_remove_comentari_comentari'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentari',
            name='comentari',
            field=models.TextField(default=3),
            preserve_default=False,
        ),
    ]
