# Generated by Django 3.2.2 on 2021-06-06 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestio_cine', '0069_comentari_comentari'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentari',
        ),
    ]
