# Generated by Django 3.2.2 on 2021-07-09 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestio_cine', '0074_remove_butaca_reserves_id_sessio'),
    ]

    operations = [
        migrations.AddField(
            model_name='butaca_reserves',
            name='id_sessio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestio_cine.sessio'),
        ),
    ]
