# Generated by Django 3.2.2 on 2021-08-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestio_cine', '0075_butaca_reserves_id_sessio'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuari',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
