# Generated by Django 3.2.2 on 2022-04-19 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestio_cine', '0076_usuari_profile_pic'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='butaca_reserves',
            unique_together={('id_butaca_reserves', 'id_reserva')},
        ),
    ]
