# Generated by Django 3.2.2 on 2022-04-19 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestio_cine', '0077_alter_butaca_reserves_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='butaca_reserves',
            unique_together=set(),
        ),
    ]
